services:
  client:
    container_name: survaanalytics_client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    env_file:
      - ./client/.env.production
    depends_on:
      - server
    networks:
      - app-network

  server:
    container_name: survaanalytics_server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    restart: unless-stopped
    networks:
      - app-network

  service_python:
    container_name: survaanalytics_service_python
    build:
      context: ./service_python
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./service_python/app/.env
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
